platform :ios, '16.0'
use_frameworks! :linkage => :static
project 'WorkoutCoach.xcodeproj'
target 'WorkoutCoach' do
  pod 'MediaPipeTasksVision', '= 1.0.0'
  target 'WorkoutCoachUnitTests' do
    inherit! :search_paths
  end
end
